def prayud():
    print ("---------------------------------------------")
    print ("|          ((  ####@@!!$$    ))             |")
    print ("|              `#####@@!$$`  ))             |")
    print ("|           ((  '####@!!$:                  |")
    print ("|         ((  ,####@!!$:   ))               |")
    print ("|             .###@!!$:                     |")
    print ("|             `##@@!$:                      |")
    print ("|               `#@!!$                      |")
    print ("|          !@#    `#@!$:       @#$          |")
    print ("|           #$     `#@!$:       !@!         |")
    print ("|                   '@!$:                   |")
    print ("|               '`\   !$: /`'               |")
    print ("|                   '\  '!: /'              |")
    print ("|                      '\ : /'              |")
    print ("---------------------------------------------")
    print ("|  Name: Grandpa Prayud(ตาประหยัด)           |")
    print ("|  Ability: Can get angry anytime           |") 
    print ("|           he want (str +99)               |")
    print ("|  Weapon: Table                            |")
    print ("|  Hobby: Do an exercise                    |")
    print ("---------------------------------------------")
