def somsri():
    print ("---------------------------------------------")
    print ("|                               /          |")
    print ("|                          ,.. /           |")
    print ("|                        ,'   ';           |")
    print ("|            ,,.__    _,' /';  .           |")
    print ("|           :','  ~~~~    '. '~            |")
    print ("|         :' (   )         )::,            |")
    print ("|         '. '. .=----=..-~  .;'           |")
    print ("|          '  ;'  ::   ':.  ''             |")
    print ("|           (:   ':    ;)                  |")
    print ("|            \\\  '    //'                  |")
    print ("|             ''      ''                   |")
    print ("---------------------------------------------")
    print ("|  Name: Grandma Somsri(ยายสมศรี)           |")
    print ("|  Ability: Very good eyesight (DEX +99)   |")
    print ("|  Weapon: Kar98k                          |")
    print ("|  Hobby: Camping in the forest            |")
    print ("---------------------------------------------")
